<?php
$this->headScript() ->appendFile('/js/twitter_feed.js', 'text/javascript');
$this->headLink()->appendStylesheet($this->basePath() . '/css/twitter_feed.css');
?>

<?php
/* @var $following EgcTweet\Entity\Following */
foreach($this->followings as $key => $following):?>
<div class="twitter-feed" id="twitter-feed-<?= $key ?>"></div>
<script type="text/javascript">
jQuery(function() {
	var el = $('#twitter-feed-<?= $key ?>');
	<?php $obj_name = "t_{$key}";?>
	var <?= $obj_name?> = new EgcTweetSpinner(
		'/twitter/timeline/<?= $following->getFollowingId() ?>.json', {
			twitterprofile: '<?= $following->getFollowingName() ?>',
			element: $(el)
		}
	);
	<?= $obj_name?>.load();
});
</script>
<?php endforeach;?>

