<?php echo $this->doctype(); ?>
<html lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta charset="utf-8">
<?php echo $this->headTitle('Parsed Cloud ')?>
<?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
?>
	<?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                ->prependStylesheet($this->basePath() . '/css/main.css')
                ->prependStylesheet($this->basePath() . '/css/reset.css')
		        ->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
                ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css')
?>

        <?php echo $this->headScript()
            ->prependFile($this->basePath() . '/js/bootstrap.min.js')
            ->prependFile($this->basePath() . '/js/jquery.min.js')
            ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>
</head>
<body>
	<div id="wrapper">
	   <div id="header">
		  <div id="logo"><a href="<?= $this->url('home')?>"><img src="/img/logo.jpg" alt="Logo tekst" /></a>
		  </div><!-- end of logo -->
		  <div id="navigation">
			<?= $this->partial('partials/user_ctl.phtml')?>
		  </div><!-- end of navigation -->
		  <div id="share">
			 <div id="btns">
				<a href="#" target="_blank"><img src="/img/twitter.png" alt="Twitter" /></a>
				<a href="#" target="_blank"><img src="/img/flickr.png" alt="Flickr" /></a>
				<a href="#" target="_blank"><img src="/img/facebook.png" alt="Facebook share" /></a>
				<a href="#" target="_blank"><img src="/img/linkedin.png" alt="Linkedin share" /></a>
				<a href="#" target="_blank"><img src="/img/rss.png" alt="Rss" /></a>
			</div>
		  </div><!-- end of share -->
	   </div><!-- end of header -->
	  <div id="mainBody">
			<div id="sideNav"> <a href="/"><img src="/img/twit_selected.png" alt="Twitter" /></a>
				<img src="/img/rss_normal.png" alt="Twitter" />
				<img src="/img/bookmarks_normal.png" alt="Twitter" />
				<img src="/img/places_normal.png" alt="Twitter" />
			</div><!--end of sideNav -->
			<div id="banners">
			   <div id="add1">
				 <img src="/img/banner1.jpg" width="468" height="60" />
			   </div>
			   <div id="add2">
				  <img src="/img/banner2.jpg" width="468" height="60" />
			   </div>
			</div>
			<div id="content">
			    <?php echo $this->content; ?>
			</div>
	   </div><!-- end of mainBody -->
	   <div id="footer">
		  <div id="copyright">
			 <h4>All rights reserved</h4>
		  </div><!-- end of copyright -->
	   </div><!-- end of footer -->
	</div><!-- end of wrapper -->
</body>
</html>
