<form class="t1-form form-search js-search-form" action="http://twitter.com/search" id="global-nav-search">

    <label class="visuallyhidden" for="search-query">Search query</label>
    <input class="search-input" type="text" id="search-query" placeholder="Search Twitter" name="q" autocomplete="off" spellcheck="false">
    <span class="search-icon js-search-action">
      <button type="submit" class="Icon Icon--search nav-search">
        <span class="visuallyhidden">Search Twitter</span>
      </button>
    </span>
      <div role="listbox" class="dropdown-menu typeahead">
</form>