<?php
$this->headScript() ->appendFile('/js/typeahead.bundle.min.js', 'text/javascript')
                    ->appendFile('/js/handlebars.js', 'text/javascript');
$this->headLink()->appendStylesheet($this->basePath() . '/css/typeahead.css');

// $this->headScript()
//     ->appendFile('/js/bloodhound.min.js', 'text/javascript')
//     ->appendFile('/js/bootstrap3-typeahead.min.js', 'text/javascript');

$form = $this->form;
$form->prepare();
$form->setAttribute('action', $this->url('egc-tweet', array(
    'controller' => 'profile',
    'action' => 'save'
)));
$form->setAttribute('method', 'post');
?>

<?php echo $this->form()->openTag($form)?>

<dl class="zend_form">
    	<?php echo $this->formCollection($form->get(EgcTweet\Form\ProfileForm::FOLLOWINGS_FIELDSET_NAME));?>

        <?php echo $this->formButton($form->get('submit'))?>
    </dl>

<?php echo $this->form()->closeTag()?>

<script type="text/javascript">

jQuery(function() {
    var users = new Bloodhound({
        datumTokenizer: function (datum) {
            return Bloodhound.tokenizers.whitespace(datum.display_name);
        },
        queryTokenizer: Bloodhound.tokenizers.whitespace,
        limit: 10,
        remote: {
            url: '/twitter/users/%QUERY.json',
            filter: function (response) {
                return $.map(response.items, function (item) {
                    return {
                        id: item.id,
                        screen_name: item.screen_name,
                        name: item.name,
                        profile_image_url: item.profile_image_url
                    };
                });
            }
        }
    });

    users.initialize();

    $('.zend_form [data-provide=typeahead]').typeahead({
        	minLength: 3,
            highlight: true,
            hint:true
        }, {
        name: 'tweeter-users',
        displayKey: 'screen_name',
        source: users.ttAdapter(),
        templates: {
        	empty: [
            	'<div style="padding:5px;color: red;" >',
            	'Unable find any user that match the current query.',
            	'</div>'
        	].join('\n'),
//         	suggestion: Handlebars.compile('<div style="margin:0; padding:2px;clear:both;"><img style="padding:4px;float:left;position:left;" src="{{profile_image_url}}"/><span style="float:left;position: relative; ">{{name}}</span> <span style="float: right; font-weight: normal !important; position: relative; font-size:10px;top: 30px;">@{{screen_name}}</span></div>')
        	suggestion: Handlebars.compile(
                ['<div class="typeahead-item typeahead-account-item js-selectable" style="overflow: hidden;">',
                '<p class="js-nav has-social-context" role="option">',
                  '<img class="profile-img size32" src="{{profile_image_url}}">',
                  '<span class="typeahead-user-item-info">',
                      '<p class="fullname">{{name}}</p>',
                      '<p class="username">@<b>{{screen_name}}</b></p>',
                  '</span>',
                '</p>',
            '</div>'].join(''))
    	},
//         displayKey: function (item) {
//             return item.display_name;
//         },
    }).on('typeahead:selected', function (obj, datum) {
        var following_name_element_name = obj.target.name,
        following_fieldset_group_name = following_name_element_name.match(/followings\[\d+\]/),
        following_id_element_name = following_fieldset_group_name+"[followingId]",
        following_id_element = $('[name="'+following_id_element_name+'"]')[0]
        if (following_id_element)
            following_id_element.value = datum.id;
    });;
});
</script>
