<?php
$this->headScript()->appendFile('/js/typeahead.bundle.min.js', 'text/javascript');

$form = $this->form;
$form->prepare();
$form->setAttribute('action', $this->url('egc-tweet', array('controller' => 'profile', 'action' => 'save')));
$form->setAttribute('method', 'post');
?>

<?php echo $this->form()->openTag($form) ?>

    <dl class="zend_form">
    	<?php echo $this->formCollection($form->get(EgcTweet\Form\ProfileForm::FOLLOWINGS_FIELDSET_NAME));?>

        <?php echo $this->formButton($form->get('submit')) ?>
    </dl>

<?php echo $this->form()->closeTag() ?>

<script type="text/javascript">

jQuery(function() {
    var bestPictures = new Bloodhound({
        datumTokenizer: Bloodhound.tokenizers.obj.whitespace('value'),
        queryTokenizer: Bloodhound.tokenizers.whitespace,
        prefetch: '/twitter/users/PHP.json',
        remote: '/twitter/users/%QUERY.json'
    });

    bestPictures.initialize();

    $('.zend_form fieldset .typeahead').typeahead(null, {
        name: 'tweeter-users',
        displayKey: 'value',
        source: bestPictures.ttAdapter()
    });
});
</script>
